language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - ".+"
script:
- chmod +x gradlew
